version: 2.x.{build}

clone_folder: C:\Project

# We use the configuration to specify the package name
configuration:
  - psycopg2
  - psycopg2-binary

environment:
  matrix:
    # For Python versions available on Appveyor, see
    # https://www.appveyor.com/docs/windows-images-software/#python
    - {PY_VER: "311", PY_ARCH: "32", APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019}
    - {PY_VER: "311", PY_ARCH: "64", APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019}
    - {PY_VER: "310", PY_ARCH: "32", APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019}
    - {PY_VER: "310", PY_ARCH: "64", APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019}
    - {PY_VER: "39", PY_ARCH: "32", APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019}
    - {PY_VER: "39", PY_ARCH: "64", APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019}
    - {PY_VER: "38", PY_ARCH: "32", APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015}
    - {PY_VER: "38", PY_ARCH: "64", APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015}
    - {PY_VER: "37", PY_ARCH: "32", APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015}
    - {PY_VER: "37", PY_ARCH: "64", APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015}

  WORKFLOW: packages

  OPENSSL_VERSION: "1_1_1t"
  POSTGRES_VERSION: "15_0"

  PSYCOPG2_TESTDB: psycopg2_test
  PSYCOPG2_TESTDB_USER: postgres
  PSYCOPG2_TESTDB_HOST: localhost

  PGUSER: postgres
  PGPASSWORD: Password12!
  PGSSLMODE: require

  # Add CWD to perl library path for PostgreSQL build on VS2019
  PERL5LIB: .

  # Select according to the service enabled
  POSTGRES_DIR: C:\Program Files\PostgreSQL\9.6\

  # The python used in the build process, not the one packages are built for
  PYEXE: C:\Python36\python.exe

matrix:
  fast_finish: false

services:
  # Note: if you change this service also change POSTGRES_DIR
  - postgresql96

cache:
  # Rebuild cache if following file changes
  # (See the file to zap the cache manually)
  - C:\Others -> .appveyor\cache_rebuild

# Script called before repo cloning
# init:

# Repository gets cloned, Cache is restored

install:
  - "%PYEXE% scripts\\build\\appveyor.py install"

# PostgreSQL server starts now

build: "off"

build_script:
  - "%PYEXE% scripts\\build\\appveyor.py build_script"

after_build:
  - "%PYEXE% scripts\\build\\appveyor.py after_build"

before_test:
  - "%PYEXE% scripts\\build\\appveyor.py before_test"

test_script:
  - "%PYEXE% scripts\\build\\appveyor.py test_script"

artifacts:
  - path: dist\psycopg2-*\*.whl
    name: wheel


# vim: set ts=4 sts=4 sw=4:
