name: Build documentation

on:
  push:
    branches:
      # This should match the DOC_BRANCH value in the psycopg-website Makefile
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger docs build
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: psycopg/psycopg-website
          event-type: psycopg2-commit
          token: ${{ secrets.ACCESS_TOKEN }}
